### ISSUE TITLE
Clean-Up

### ISSUE THREAD

**Issue by tvatter** [vinecopulib/vinecopulib#54]
[Edit with items from the discussion, sorted by (arguable) order in which tasks should be dealt with)]

As discussed, it is now time for a clean-up:
- [ ] Beef up Appveyor builds #44 
- [x] Make subfolders bicop/vinecop/tools in src and include
- [x] Update documentation everywhere
- [x] Update readme (e.g., for R dependencies)

Done:
- [x] replacing #ifndex/#define/#endif constructs with #pragma once #34
- [x] silence preprocessor redefinition warnings #28 
- [x] switch to the MIT license
- [x] getting rid of Rcpp/REigen/RInside dependencies #20
- [x] Move all STL-based utility-functions into new header std_tools.hpp.
- [x] Moving `#includes` from .hpp into .cpp files whenever possible.
- [x] Adapt `Bicop::select()` arguments and their order to `Vinecop::select()`.
- [x] Remove include/git_revision.h file from the repo
- [x] Create tools_bicopselect.cpp/hpp for `preselect_family` and `get_c1c2
- [x] Add CMake option to compile library without unit tests #20
- [x] vinecopulib namespace #32
- [x] Consistent placement of doxygen blocks.
- [x] Create vinecopulib-config.cmake #42
- [x] Include coverage test
- [x] Change the enumeration of the families #7

**Comment by tnagler** [comment]
Few more additions, up for discussion: 
- [ ] Move all STL-based utility-functions into new header std_tools.hpp (makes more sense here than in vinecop refactoring).
- [ ] Consistent placement of doxygen blocks (I'd prefer in .cpp files).
- [ ] Moving `#includes` from .hpp into .cpp files whenever possible (having them in headers slows down building the library).

Regarding your questions:
1. Yeah, but we should first agree on a system ;)
2. Good idea. Ahmad was looking into different licenses further and suggested that MIT might be better, because it explicitly allows for sublicensing (which we probably need for the R package). Otherwise BSD/MIT are quite similar as far as I understand.
3. Good idea.

**Comment by tvatter** [comment]
Agreed with the three propositions above!

1. I answered in #7.
2. I'm fine with MIT. I just want to avoid GPL and similar.

**Comment by tvatter** [comment]
I opened a new branch for this stuff.

**Comment by tnagler** [comment]
One more that we shouldn't forget:
- [ ] Adapt `Bicop::select()` arguments and their order to `Vinecop::select()`.

**Comment by tvatter** [comment]
How about also adding a coverage test?

**Comment by slayoo** [comment]
I suggest also:
- [ ] removing include/git_revision.h file from the repo (and future release tarball) - it is automatically generated by CMake, and if included in the repo it has by-design invalid content

**Comment by tvatter** [comment]
I don't even know what this file is and what it does...

**Comment by slayoo** [comment]
I've added the CMake logic to generate it to enable the users to do something like:

```python
import pyvinecopulib
print(pyvinecopulib.git_revision)
```

(similarily in C++)

**Comment by tnagler** [comment]
So you're saying, we should delete it and put it on gitignore?

**Comment by tvatter** [comment]
In the same spirit as rscript.hpp, generated files should go into the /generated/ subfolder of the build folder in order to avoid this kind of issue!

**Comment by slayoo** [comment]
good idea, let's just remember to add additional "install" rule to get the file installed along with all the header files from "include"

**Comment by slayoo** [comment]
Of course, extension does not matter

**Comment by tvatter** [comment]
Except when we're trying to be somewhat consistent within the project...

**Comment by tnagler** [comment]
If I understand correctly, the file must go into `include/` eventually so that users can access it without additional hustle?

**Comment by tvatter** [comment]
Why? And is there a difference with rscript.hpp?

**Comment by tnagler** [comment]
You explicitly include this directory for the tests, a user wouldn't do that.

**Comment by tvatter** [comment]
Hmmm, OK, then it's indeed different from Rscript...

**Comment by tnagler** [comment]
So delete + gitingore?

**Comment by tvatter** [comment]
I would remove it completely and use a proper version name. I don't see the point of dragging this stuff along, unless there is a good reason to do so.

**Comment by slayoo** [comment]
The possibility of annotating simulation output with precise version number is the key reason, in my opinion. In the days of github, it seems quite probably that users will also use non-release versions...

BTW, the file needs to be shipped in release tarballs.

**Comment by tnagler** [comment]
Makes sense, then let's leave it as is.

**Comment by tvatter** [comment]
A few questions:

1. inverse_permutation/to_upper_tri => should they be in the vinecopulib namespace? Same for relabel_one/relabel_elements?
2. Should we write tools_hinv.hpp/cpp for qcondjoe/qcondgumbel (and probably other when I'll find time to add them)?
3. Which header do we want to install in e.g. `/usr/local/include/vinecopulib` when doing `make install`? Currently, I added the whole include folder.

**Comment by slayoo** [comment]
Quick question: why do we need the first argument for ```Vinecop::simulate(int n, const MatXd& U);```? The number of rows in U must be n.

**Comment by tnagler** [comment]
That's true, it's essentially a relict from VineCopula. I'll remove it.

**Comment by tvatter** [comment]
In fact, there should be 2 simulate functions taking different arguments: one taking `n`and the other taking `U`. I personally use the `n` argument far more often than the `U` ;)

**Comment by tnagler** [comment]
Yep, that's what I'm doing.

**Comment by tnagler** [comment]
I renamed `simulate(U)` to `inverse_rosenblatt(U)` in ab44568b1357a8220b0c02e76ce0f51eb0b9e765 since it actually calculates the inverse Rosenblatt transform (which can be used for simualtion when `U` contains independent uniform random numbers).

**Comment by slayoo** [comment]
Warnings from Appveyor:
- [ ] vinecopulib\src\vinecop\rvine_matrix.cpp(144): warning C4018: '<': signed/unsigned mismatch
- [ ] vinecopulib\src\misc\tools_stats.cpp(24): warning C4018: '<': signed/unsigned mismatch 
- [ ] vinecopulib\src\misc\tools_optimization.cpp(55): warning C4244: '=': conversion from 'double' to 'int', possible loss of data
- [ ] vinecopulib\src\bicop\tools_bicopselect.cpp(63): warning C4244: 'initializing': conversion from 'double' to 'int', possible loss of data
- [ ] vinecopulib\src\bicop\tools_bicopselect.cpp(62): warning C4244: 'initializing': conversion from 'double' to 'int', possible loss of data
